### PR TITLE
feat: add support of folke/snacks.nvim notifications

### PR DESCRIPTION
**Pull request by lvim-tech**

### CODE REVIEW

**Comment by coffebar** [comment]
What this for? If you will do multiple upload\download actions in parallel, you should see notifications for each upload, to make sure everything went successfully or not

**Comment by lvim-tech** [comment]
`
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: .../share/nvim/lazy/transfer.nvim/lua/transfer/transfer.lua:222: attempt to index local 'notification' (a number value)
`

**Comment by coffebar** [comment]
Do you using [rcarriga/nvim-notify](https://github.com/rcarriga/nvim-notify) ? Can you point any documentation related to id field? 
Here is usage example [in wiki](https://github.com/rcarriga/nvim-notify/wiki/Usage-Recipes#progress-updates) and there is no any ids required. 
Also I can't reproduce your issue with or without nvim-notify. And don't see any difference how it works before and after your changes

**Comment by lvim-tech** [comment]
I use https://github.com/folke/snacks.nvim
```
-- to replace an existing notification just use the same id.
-- you can also use the return value of the notify function as id.
for i = 1, 10 do
  vim.defer_fn(function()
    vim.notify("Hello " .. i, "info", { id = "test" })
  end, i * 500)
end
```
The latest commit adds support for Snacks

**Pull request merged**
